version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.10

    working_directory: /go/src/github.com/muiscript/ether
    steps:
      - checkout

      - run:
          name: go fmt
          command: test -z "$(gofmt -s -l . | tee /dev/stderr)"

      - run:
          name: go test
          command: go test -v ./...
